# Generated by Django 3.0.7 on 2020-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='wcphoto',
            field=models.ImageField(upload_to='wcphotos/%Y/%m/%d'),
        ),
    ]
